local M = {}

function M.get(C, R)
  return {
    Comment = R.comment,
    Constant = { fg = C.purple },
    String = R.string,
    Character = { fg = C.yellow },
    Number = { fg = C.purple },
    Boolean = { fg = C.purple },
    Float = { fg = C.purple },
    Identifier = R.identifier,
    Function = R.function_name,
    Statement = R.keyword,
    Conditional = R.keyword,
    Repeat = R.keyword,
    Label = { fg = C.subtle },
    Operator = R.operator,
    Keyword = R.keyword,
    Exception = R.keyword,
    PreProc = { fg = C.pink },
    Include = { fg = C.pink },
    Define = { fg = C.pink },
    Macro = { fg = C.purple },
    PreCondit = { fg = C.pink },
    StorageClass = { fg = C.pink },
    Structure = { fg = C.cyan },
    Typedef = { fg = C.cyan },
    Type = R.type,
    Special = { fg = C.orange },
    SpecialChar = { fg = C.orange },
    Tag = { fg = C.pink },
    Delimiter = { fg = C.fg },
    SpecialComment = { fg = C.pink },
    Debug = { fg = C.red },
    Underlined = { fg = C.cyan, underline = true },
    Ignore = { fg = C.subtle },
    Error = { fg = C.red },
    Todo = { fg = C.bg, bg = C.pink, bold = true },
    Conceal = { fg = C.cyan },
    ErrorMsg = { fg = C.red },
    MoreMsg = { fg = C.green },
    ModeMsg = { fg = C.cyan },
    SpellBad = { undercurl = true, sp = C.red },
    SpellCap = { undercurl = true, sp = C.cyan },
    SpellLocal = { undercurl = true, sp = C.orange },
    SpellRare = { undercurl = true, sp = C.purple },
    DiagnosticDeprecated = { fg = C.subtle, strikethrough = true },
    DiagnosticUnnecessary = { fg = C.subtle },
    QuickFixLine = { bg = C.bg_selection },
  }
end

return M
