local M = {}
local T = require("spectra.util.theme")

function M.get(C, R)
  return {
    Comment = R.comment,
    Constant = T.highlight(R, { "constant" }, { fg = C.purple }),
    String = R.string,
    Character = T.highlight(R, { "character", "string" }, { fg = C.yellow }),
    Number = T.highlight(R, { "number", "constant" }, { fg = C.purple }),
    Boolean = T.highlight(R, { "number", "constant" }, { fg = C.purple }),
    Float = T.highlight(R, { "number", "constant" }, { fg = C.purple }),
    Identifier = R.identifier,
    Function = R.function_name,
    Statement = R.keyword,
    Conditional = R.keyword,
    Repeat = R.keyword,
    Label = T.highlight(R, { "label", "text" }, { fg = C.subtle }),
    Operator = R.operator,
    Keyword = R.keyword,
    Exception = R.keyword,
    PreProc = T.highlight(R, { "preproc", "keyword" }, { fg = C.pink }),
    Include = T.highlight(R, { "preproc", "keyword" }, { fg = C.pink }),
    Define = T.highlight(R, { "preproc", "keyword" }, { fg = C.pink }),
    Macro = T.highlight(R, { "macro", "constant" }, { fg = C.purple }),
    PreCondit = T.highlight(R, { "preproc", "keyword" }, { fg = C.pink }),
    StorageClass = T.highlight(R, { "keyword", "preproc" }, { fg = C.pink }),
    Structure = T.highlight(R, { "type", "module" }, { fg = C.cyan }),
    Typedef = T.highlight(R, { "type", "module" }, { fg = C.cyan }),
    Type = R.type,
    Special = T.highlight(R, { "special", "escape" }, { fg = C.orange }),
    SpecialChar = T.highlight(R, { "special", "escape" }, { fg = C.orange }),
    Tag = T.highlight(R, { "tag", "keyword" }, { fg = C.pink }),
    Delimiter = { fg = C.fg },
    SpecialComment = T.highlight(R, { "preproc", "comment" }, { fg = C.pink }),
    Debug = { fg = C.red },
    Underlined = T.highlight(R, { "uri", "module" }, { fg = C.cyan }, { underline = true }),
    Ignore = { fg = C.subtle },
    Error = { fg = C.red },
    Todo = T.highlight(R, { "todo", "keyword" }, { fg = C.bg, bg = C.pink, bold = true }),
    Conceal = T.highlight(R, { "module", "type" }, { fg = C.cyan }),
    ErrorMsg = { fg = C.red },
    MoreMsg = { fg = C.green },
    ModeMsg = { fg = C.cyan },
    SpellBad = { undercurl = true, sp = C.red },
    SpellCap = { undercurl = true, sp = C.cyan },
    SpellLocal = { undercurl = true, sp = C.orange },
    SpellRare = { undercurl = true, sp = C.purple },
    DiagnosticDeprecated = { fg = C.subtle, strikethrough = true },
    DiagnosticUnnecessary = { fg = C.subtle },
    QuickFixLine = { bg = C.bg_selection },
  }
end

return M
