local M = {}

local palettes = {
  wave = {
    sumiInk0 = "#16161D",
    sumiInk1 = "#181820",
    sumiInk2 = "#1a1a22",
    sumiInk3 = "#1F1F28",
    sumiInk4 = "#2A2A37",
    sumiInk5 = "#363646",
    sumiInk6 = "#54546D",
    waveBlue1 = "#223249",
    waveBlue2 = "#2D4F67",
    winterGreen = "#2B3328",
    winterYellow = "#49443C",
    winterRed = "#43242B",
    autumnGreen = "#76946A",
    autumnRed = "#C34043",
    autumnYellow = "#DCA561",
    samuraiRed = "#E82424",
    roninYellow = "#FF9E3B",
    waveAqua1 = "#6A9589",
    dragonBlue = "#658594",
    oldWhite = "#C8C093",
    fujiWhite = "#DCD7BA",
    fujiGray = "#727169",
    oniViolet = "#957FB8",
    oniViolet2 = "#b8b4d0",
    crystalBlue = "#7E9CD8",
    springViolet1 = "#938AA9",
    springViolet2 = "#9CABCA",
    springBlue = "#7FB4CA",
    waveAqua2 = "#7AA89F",
    springGreen = "#98BB6C",
    boatYellow2 = "#C0A36E",
    carpYellow = "#E6C384",
    sakuraPink = "#D27E99",
    waveRed = "#E46876",
    peachRed = "#FF5D62",
    surimiOrange = "#FFA066",
    katanaGray = "#717C7C",
    background = "dark",
  },
  dragon = {
    dragonBlack0 = "#0d0c0c",
    dragonBlack1 = "#12120f",
    dragonBlack2 = "#1D1C19",
    dragonBlack3 = "#181616",
    dragonBlack4 = "#282727",
    dragonBlack5 = "#393836",
    dragonBlack6 = "#625e5a",
    waveBlue1 = "#223249",
    waveBlue2 = "#2D4F67",
    winterGreen = "#2B3328",
    winterYellow = "#49443C",
    winterRed = "#43242B",
    autumnGreen = "#76946A",
    autumnRed = "#C34043",
    autumnYellow = "#DCA561",
    samuraiRed = "#E82424",
    roninYellow = "#FF9E3B",
    waveAqua1 = "#6A9589",
    dragonBlue = "#658594",
    oldWhite = "#C8C093",
    fujiWhite = "#DCD7BA",
    dragonWhite = "#c5c9c5",
    dragonGreen = "#87a987",
    dragonGreen2 = "#8a9a7b",
    dragonPink = "#a292a3",
    dragonOrange = "#b6927b",
    dragonOrange2 = "#b98d7b",
    dragonGray = "#a6a69c",
    dragonGray2 = "#9e9b93",
    dragonGray3 = "#7a8382",
    dragonBlue2 = "#8ba4b0",
    dragonViolet = "#8992a7",
    dragonRed = "#c4746e",
    dragonAqua = "#8ea4a2",
    dragonAsh = "#737c73",
    dragonTeal = "#949fb5",
    dragonYellow = "#c4b28a",
    waveRed = "#E46876",
    springBlue = "#7FB4CA",
    springViolet1 = "#938AA9",
    waveAqua2 = "#7AA89F",
    carpYellow = "#E6C384",
    katanaGray = "#717C7C",
    background = "dark",
  },
  lotus = {
    sumiInk3 = "#1F1F28",
    lotusInk1 = "#545464",
    lotusInk2 = "#43436c",
    lotusGray = "#dcd7ba",
    lotusGray2 = "#716e61",
    lotusGray3 = "#8a8980",
    lotusWhite0 = "#d5cea3",
    lotusWhite1 = "#dcd5ac",
    lotusWhite2 = "#e5ddb0",
    lotusWhite3 = "#f2ecbc",
    lotusWhite4 = "#e7dba0",
    lotusWhite5 = "#e4d794",
    lotusViolet1 = "#a09cac",
    lotusViolet2 = "#766b90",
    lotusViolet3 = "#c9cbd1",
    lotusViolet4 = "#624c83",
    lotusBlue1 = "#c7d7e0",
    lotusBlue2 = "#b5cbd2",
    lotusBlue3 = "#9fb5c9",
    lotusBlue4 = "#4d699b",
    lotusBlue5 = "#5d57a3",
    lotusGreen = "#6f894e",
    lotusGreen2 = "#6e915f",
    lotusGreen3 = "#b7d0ae",
    lotusPink = "#b35b79",
    lotusOrange = "#cc6d00",
    lotusOrange2 = "#e98a00",
    lotusYellow = "#77713f",
    lotusYellow2 = "#836f4a",
    lotusYellow3 = "#de9800",
    lotusYellow4 = "#f9d791",
    lotusRed = "#c84053",
    lotusRed2 = "#d7474b",
    lotusRed3 = "#e82424",
    lotusRed4 = "#d9a594",
    lotusAqua = "#597b75",
    lotusAqua2 = "#5e857a",
    lotusTeal1 = "#4e8ca2",
    lotusTeal2 = "#6693bf",
    lotusTeal3 = "#5a7785",
    lotusCyan = "#d7e3d8",
    background = "light",
  },
}

local function enrich_palette(flavour, C)
  if flavour == "wave" then
    return {
      bg = C.sumiInk3,
      bg_dark = C.sumiInk1,
      bg_darker = C.sumiInk0,
      bg_float = C.sumiInk0,
      bg_visual = C.waveBlue1,
      bg_cursorline = C.sumiInk4,
      bg_selection = C.waveBlue1,
      fg = C.fujiWhite,
      fg_muted = C.oldWhite,
      fg_parameter = C.oniViolet2,
      comment = C.fujiGray,
      subtle = C.sumiInk6,
      gutter = C.sumiInk4,
      guide = C.sumiInk5,
      border = C.sumiInk6,
      cyan = C.springBlue,
      green = C.springGreen,
      orange = C.surimiOrange,
      amber = C.carpYellow,
      pink = C.sakuraPink,
      purple = C.oniViolet,
      red = C.waveRed,
      yellow = C.boatYellow2,
      sky = C.crystalBlue,
      teal = C.waveAqua2,
      braces = C.springBlue,
      brackets = C.waveAqua2,
      parens = C.carpYellow,
      rainbow = {
        C.oniViolet,
        C.sakuraPink,
        C.surimiOrange,
        C.springGreen,
        C.springBlue,
        C.crystalBlue,
      },
      line_nr = C.sumiInk6,
      cursorline_nr = C.carpYellow,
      match_paren_bg = C.waveBlue2,
      none = "NONE",
      terminal = {
        C.sumiInk0,
        C.autumnRed,
        C.autumnGreen,
        C.boatYellow2,
        C.crystalBlue,
        C.oniViolet,
        C.waveAqua1,
        C.oldWhite,
        C.fujiGray,
        C.samuraiRed,
        C.springGreen,
        C.carpYellow,
        C.springBlue,
        C.springViolet1,
        C.waveAqua2,
        C.fujiWhite,
      },
    }
  end

  if flavour == "dragon" then
    return {
      bg = C.dragonBlack3,
      bg_dark = C.dragonBlack1,
      bg_darker = C.dragonBlack0,
      bg_float = C.dragonBlack0,
      bg_visual = C.waveBlue1,
      bg_cursorline = C.dragonBlack4,
      bg_selection = C.waveBlue1,
      fg = C.dragonWhite,
      fg_muted = C.oldWhite,
      fg_parameter = C.dragonGray,
      comment = C.dragonAsh,
      subtle = C.dragonGray3,
      gutter = C.dragonBlack4,
      guide = C.dragonBlack5,
      border = C.dragonGray3,
      cyan = C.dragonTeal,
      green = C.dragonGreen2,
      orange = C.dragonOrange,
      amber = C.dragonYellow,
      pink = C.dragonPink,
      purple = C.dragonViolet,
      red = C.dragonRed,
      yellow = C.dragonYellow,
      sky = C.dragonBlue2,
      teal = C.dragonAqua,
      braces = C.dragonBlue2,
      brackets = C.dragonAqua,
      parens = C.dragonYellow,
      rainbow = {
        C.dragonViolet,
        C.dragonPink,
        C.dragonOrange,
        C.dragonGreen2,
        C.dragonAqua,
        C.dragonBlue2,
      },
      line_nr = C.dragonBlack6,
      cursorline_nr = C.dragonYellow,
      match_paren_bg = C.waveBlue2,
      none = "NONE",
      terminal = {
        C.dragonBlack0,
        C.dragonRed,
        C.dragonGreen2,
        C.dragonYellow,
        C.dragonBlue2,
        C.dragonPink,
        C.dragonAqua,
        C.oldWhite,
        C.dragonGray,
        C.waveRed,
        C.dragonGreen,
        C.carpYellow,
        C.springBlue,
        C.springViolet1,
        C.waveAqua2,
        C.dragonWhite,
      },
    }
  end

  return {
    bg = C.lotusWhite3,
    bg_dark = C.lotusWhite1,
    bg_darker = C.lotusWhite0,
    bg_float = C.lotusWhite0,
    bg_visual = C.lotusViolet3,
    bg_cursorline = C.lotusWhite4,
    bg_selection = C.lotusViolet3,
    fg = C.lotusInk1,
    fg_muted = C.lotusInk2,
    fg_parameter = C.lotusBlue5,
    comment = C.lotusGray3,
    subtle = C.lotusViolet1,
    gutter = C.lotusWhite4,
    guide = C.lotusGray3,
    border = C.lotusGray2,
    cyan = C.lotusTeal2,
    green = C.lotusGreen,
    orange = C.lotusOrange,
    amber = C.lotusYellow2,
    pink = C.lotusPink,
    purple = C.lotusViolet4,
    red = C.lotusRed,
    yellow = C.lotusYellow,
    sky = C.lotusBlue4,
    teal = C.lotusAqua,
    braces = C.lotusBlue4,
    brackets = C.lotusAqua,
    parens = C.lotusYellow2,
    rainbow = {
      C.lotusViolet4,
      C.lotusPink,
      C.lotusOrange,
      C.lotusGreen,
      C.lotusTeal2,
      C.lotusBlue4,
    },
    line_nr = C.lotusGray3,
    cursorline_nr = C.lotusOrange2,
    match_paren_bg = C.lotusBlue2,
    none = "NONE",
    terminal = {
      C.sumiInk3,
      C.lotusRed,
      C.lotusGreen,
      C.lotusYellow,
      C.lotusBlue4,
      C.lotusPink,
      C.lotusAqua,
      C.lotusInk1,
      C.lotusGray3,
      C.lotusRed2,
      C.lotusGreen2,
      C.lotusYellow2,
      C.lotusTeal2,
      C.lotusViolet4,
      C.lotusAqua2,
      C.lotusInk2,
    },
  }
end

local function roles(flavour)
  return function(C, O)
    local styles = O.styles or {}
    local is_lotus = flavour == "lotus"
    local tag = is_lotus and C.red or C.red
    local builtin = is_lotus and C.orange or C.orange
    local property = is_lotus and C.amber or C.amber

    return {
      text = { fg = C.fg },
      identifier = { fg = C.amber },
      local_variable = { fg = C.fg },
      builtin_variable = { fg = builtin },
      comment = { fg = C.comment, italic = vim.tbl_contains(styles.comments or {}, "italic") },
      keyword = { fg = C.purple },
      preproc = { fg = C.red },
      function_name = { fg = C.sky },
      function_builtin = { fg = C.cyan },
      type = { fg = C.teal },
      builtin_type = { fg = C.teal },
      type_parameter = { fg = C.amber },
      constructor = { fg = C.teal },
      parameter = { fg = C.fg_parameter, italic = vim.tbl_contains(styles.parameters or {}, "italic") },
      label = { fg = C.orange },
      field = { fg = property },
      property = { fg = property },
      constant = { fg = C.orange },
      macro = { fg = C.red },
      string = { fg = C.green },
      character = { fg = C.green },
      number = { fg = C.pink },
      escape = { fg = C.red },
      regexp = { fg = C.yellow },
      special = { fg = C.cyan },
      tag = { fg = tag },
      attribute = { fg = C.amber },
      operator = { fg = C.yellow },
      module = { fg = C.teal },
      uri = { fg = C.sky, underline = true },
      todo = { fg = C.bg, bg = C.yellow, bold = true },
      diagnostic_error = { fg = C.red },
      diagnostic_warn = { fg = C.orange },
      diagnostic_info = { fg = C.sky },
      diagnostic_hint = { fg = C.teal },
      ui_border = { fg = C.border },
      ui_selection = { bg = C.bg_selection },
      ui_menu = { fg = C.fg, bg = C.bg_float },
    }
  end
end

local function editor_overrides(flavour, raw, C)
  if flavour == "lotus" then
    return {
      FloatTitle = { fg = C.lotusBlue4, bg = C.lotusWhite0 },
      CursorLineNr = { fg = C.lotusOrange2, bold = true },
      MatchParen = { fg = C.lotusInk1, bg = C.lotusBlue2, bold = true },
      LineNr = { fg = C.lotusGray3 },
      EndOfBuffer = { fg = C.lotusWhite4 },
      WildMenu = { fg = C.lotusWhite0, bg = C.lotusViolet4, bold = true },
      Pmenu = { fg = C.lotusInk2, bg = C.lotusBlue1 },
      PmenuSel = { fg = C.lotusInk2, bg = C.lotusBlue3 },
      PmenuThumb = { bg = C.lotusBlue2 },
    }
  end

  local accent = flavour == "dragon" and raw.dragonYellow or raw.carpYellow
  local title = flavour == "dragon" and raw.dragonBlue2 or raw.crystalBlue
  local line = flavour == "dragon" and raw.dragonBlack6 or raw.sumiInk6
  local wild = flavour == "dragon" and raw.dragonViolet or raw.oniViolet

  return {
    FloatTitle = { fg = title, bg = C.bg_float },
    CursorLineNr = { fg = accent, bold = true },
    MatchParen = { fg = C.fg, bg = raw.waveBlue2, bold = true },
    LineNr = { fg = line },
    EndOfBuffer = { fg = line },
    WildMenu = { fg = C.bg, bg = wild, bold = true },
    Pmenu = { fg = C.fg, bg = C.bg_float },
    PmenuSel = { fg = C.fg, bg = C.bg_selection },
    PmenuThumb = { bg = wild },
  }
end

local function syntax_overrides(flavour, C)
  local type_fg = flavour == "lotus" and C.lotusAqua or (flavour == "dragon" and C.dragonAqua or C.waveAqua2)

  return {
    Character = { fg = C.green },
    Constant = { fg = C.orange },
    Number = { fg = C.pink },
    Boolean = { fg = C.pink },
    Float = { fg = C.pink },
    StorageClass = { fg = C.purple },
    Structure = { fg = type_fg },
    Special = { fg = C.cyan },
    SpecialChar = { fg = C.red },
    Tag = { fg = C.red },
    Conceal = { fg = C.subtle },
    MoreMsg = { fg = C.sky },
    ModeMsg = { fg = C.sky },
    Todo = { fg = C.bg, bg = C.yellow, bold = true },
  }
end

local function treesitter_overrides(C)
  return {
    ["@variable"] = { fg = C.fg },
    ["@variable.builtin"] = { fg = C.orange },
    ["@variable.parameter"] = { fg = C.fg_parameter },
    ["@variable.member"] = { fg = C.amber },
    ["@constant"] = { fg = C.orange },
    ["@constant.builtin"] = { fg = C.orange },
    ["@constant.macro"] = { fg = C.red },
    ["@module"] = { fg = C.teal },
    ["@string.documentation"] = { fg = C.comment },
    ["@string.escape"] = { fg = C.red },
    ["@string.special.symbol"] = { fg = C.orange },
    ["@type.builtin"] = { fg = C.teal },
    ["@attribute"] = { fg = C.amber },
    ["@property"] = { fg = C.amber },
    ["@function.builtin"] = { fg = C.cyan },
    ["@function.macro"] = { fg = C.red },
    ["@constructor"] = { fg = C.teal },
    ["@keyword.import"] = { fg = C.purple },
    ["@keyword.return"] = { fg = C.red },
    ["@keyword.operator"] = { fg = C.yellow },
    ["@punctuation.bracket"] = { fg = C.fg_muted },
    ["@markup.link"] = { fg = C.sky, underline = true },
    ["@markup.link.label"] = { fg = C.cyan },
    ["@markup.link.url"] = { fg = C.sky, underline = true, italic = true },
    ["@markup.quote"] = { fg = C.comment },
    ["@tag"] = { fg = C.red },
    ["@tag.builtin"] = { fg = C.red },
    ["@tag.attribute"] = { fg = C.amber },
    ["@tag.delimiter"] = { fg = C.cyan },
    ["@comment.todo"] = { fg = C.bg, bg = C.yellow, bold = true },
    ["@comment.note"] = { fg = C.bg, bg = C.sky, bold = true },
    ["@comment.warning"] = { fg = C.bg, bg = C.orange, bold = true },
    ["@comment.error"] = { fg = C.bg, bg = C.red, bold = true },
    ["@markup.heading.1.markdown"] = { fg = C.red, bold = true },
    ["@markup.heading.2.markdown"] = { fg = C.orange, bold = true },
    ["@markup.heading.3.markdown"] = { fg = C.yellow, bold = true },
    ["@markup.heading.4.markdown"] = { fg = C.green, bold = true },
    ["@markup.heading.5.markdown"] = { fg = C.cyan, bold = true },
    ["@markup.heading.6.markdown"] = { fg = C.purple, bold = true },
    ["@property.css"] = { fg = C.sky },
    ["@property.scss"] = { fg = C.sky },
    ["@property.id.css"] = { fg = C.amber },
    ["@property.class.css"] = { fg = C.amber },
    ["@type.css"] = { fg = C.teal },
    ["@type.tag.css"] = { fg = C.red },
    ["@number.css"] = { fg = C.pink },
    ["@string.special.url.html"] = { fg = C.green, underline = true },
    ["@markup.link.label.html"] = { fg = C.fg },
    ["@character.special.html"] = { fg = C.red },
    ["@attribute.c_sharp"] = { fg = C.amber },
  }
end

local function semantic_token_overrides(C)
  return {
    ["@lsp.type.enumMember"] = { fg = C.orange },
    ["@lsp.type.parameter"] = { fg = C.fg_parameter },
    ["@lsp.type.property"] = { fg = C.amber },
    ["@lsp.type.variable.readonly"] = { fg = C.orange, bold = true },
    ["@lsp.typemod.function.defaultLibrary"] = { link = "@function.builtin" },
    ["@lsp.typemod.function.builtin"] = { link = "@function.builtin" },
    ["@lsp.typemod.property.defaultLibrary"] = { fg = C.amber },
    ["@lsp.typemod.variable.defaultLibrary"] = { fg = C.orange },
    ["@lsp.typemod.variable.globalScope"] = { fg = C.orange, bold = true },
    ["@lsp.typemod.variable.readonly"] = { fg = C.orange, bold = true },
    ["@lsp.typemod.variable.static"] = { fg = C.orange, bold = true },
  }
end

local function shared_overrides(flavour, raw, palette)
  return {
    modules = {
      editor = function()
        return editor_overrides(flavour, raw, palette)
      end,
      syntax = function()
        return syntax_overrides(flavour, palette)
      end,
      treesitter = function()
        return treesitter_overrides(palette)
      end,
      semantic_tokens = function()
        return semantic_token_overrides(palette)
      end,
    },
    integrations = {},
    languages = {},
  }
end

function M.make(flavour)
  local raw = palettes[flavour]
  if not raw then
    error("spectra.nvim: unknown Kanagawa flavour '" .. tostring(flavour) .. "'")
  end

  local colorscheme = "kanagawa-" .. flavour
  local palette = enrich_palette(flavour, raw)

  return {
    meta = {
      name = colorscheme,
      colorscheme = colorscheme,
      background = raw.background,
      family = "kanagawa",
      flavour = flavour,
    },
    palette = function()
      return vim.deepcopy(palette)
    end,
    roles = roles(flavour),
    overrides = shared_overrides(flavour, raw, palette),
  }
end

return M
