local M = {}

local palettes = {
  moon = {
    bg = "#222436",
    bg_dark = "#1e2030",
    bg_darker = "#191b29",
    bg_float = "#1e2030",
    bg_visual = "#2f334d",
    bg_cursorline = "#2a2e45",
    bg_selection = "#2f334d",
    fg = "#c8d3f5",
    fg_muted = "#a9b8e8",
    fg_parameter = "#c099ff",
    comment = "#7a88cf",
    subtle = "#6f7bb6",
    gutter = "#2a2e45",
    guide = "#3b4261",
    border = "#3b4261",
    cyan = "#86e1fc",
    green = "#c3e88d",
    orange = "#ff966c",
    amber = "#ffc777",
    pink = "#fca7ea",
    purple = "#c099ff",
    red = "#ff757f",
    yellow = "#ffc777",
    sky = "#82aaff",
    teal = "#4fd6be",
    blue = "#82aaff",
    magenta = "#c099ff",
    braces = "#82aaff",
    brackets = "#4fd6be",
    parens = "#ffc777",
    rainbow = {
      "#c099ff",
      "#fca7ea",
      "#ff966c",
      "#c3e88d",
      "#86e1fc",
      "#82aaff",
    },
    none = "NONE",
    terminal = {
      "#1b1d2b",
      "#ff757f",
      "#c3e88d",
      "#ffc777",
      "#82aaff",
      "#fca7ea",
      "#86e1fc",
      "#c8d3f5",
      "#444a73",
      "#ff8d94",
      "#c7fb6d",
      "#ffd8ab",
      "#9ab8ff",
      "#fca7ea",
      "#b4f9f8",
      "#c8d3f5",
    },
    background = "dark",
  },
  storm = {
    bg = "#24283b",
    bg_dark = "#1f2335",
    bg_darker = "#1b1f2f",
    bg_float = "#1f2335",
    bg_visual = "#2e334d",
    bg_cursorline = "#292e42",
    bg_selection = "#2e334d",
    fg = "#c0caf5",
    fg_muted = "#9aa5ce",
    fg_parameter = "#bb9af7",
    comment = "#565f89",
    subtle = "#565f89",
    gutter = "#292e42",
    guide = "#3b4261",
    border = "#3b4261",
    cyan = "#7dcfff",
    green = "#9ece6a",
    orange = "#ff9e64",
    amber = "#e0af68",
    pink = "#f7768e",
    purple = "#bb9af7",
    red = "#f7768e",
    yellow = "#e0af68",
    sky = "#7aa2f7",
    teal = "#73daca",
    blue = "#7aa2f7",
    magenta = "#bb9af7",
    braces = "#7aa2f7",
    brackets = "#73daca",
    parens = "#e0af68",
    rainbow = {
      "#bb9af7",
      "#f7768e",
      "#ff9e64",
      "#9ece6a",
      "#7dcfff",
      "#7aa2f7",
    },
    none = "NONE",
    terminal = {
      "#1d202f",
      "#f7768e",
      "#9ece6a",
      "#e0af68",
      "#7aa2f7",
      "#bb9af7",
      "#7dcfff",
      "#c0caf5",
      "#414868",
      "#ff899d",
      "#9fe044",
      "#faba4a",
      "#8db0ff",
      "#c7a9ff",
      "#a4daff",
      "#c0caf5",
    },
    background = "dark",
  },
  night = {
    bg = "#1a1b26",
    bg_dark = "#16161e",
    bg_darker = "#11121a",
    bg_float = "#16161e",
    bg_visual = "#283457",
    bg_cursorline = "#1f2335",
    bg_selection = "#283457",
    fg = "#c0caf5",
    fg_muted = "#9aa5ce",
    fg_parameter = "#bb9af7",
    comment = "#565f89",
    subtle = "#565f89",
    gutter = "#1f2335",
    guide = "#30374f",
    border = "#30374f",
    cyan = "#7dcfff",
    green = "#9ece6a",
    orange = "#ff9e64",
    amber = "#e0af68",
    pink = "#f7768e",
    purple = "#bb9af7",
    red = "#f7768e",
    yellow = "#e0af68",
    sky = "#7aa2f7",
    teal = "#73daca",
    blue = "#7aa2f7",
    magenta = "#bb9af7",
    braces = "#7aa2f7",
    brackets = "#73daca",
    parens = "#e0af68",
    rainbow = {
      "#bb9af7",
      "#f7768e",
      "#ff9e64",
      "#9ece6a",
      "#7dcfff",
      "#7aa2f7",
    },
    none = "NONE",
    terminal = {
      "#15161e",
      "#f7768e",
      "#9ece6a",
      "#e0af68",
      "#7aa2f7",
      "#bb9af7",
      "#7dcfff",
      "#c0caf5",
      "#414868",
      "#ff899d",
      "#9fe044",
      "#faba4a",
      "#8db0ff",
      "#c7a9ff",
      "#a4daff",
      "#c0caf5",
    },
    background = "dark",
  },
  day = {
    bg = "#e1e2e7",
    bg_dark = "#d5d6db",
    bg_darker = "#c9cad1",
    bg_float = "#d5d6db",
    bg_visual = "#c4c8da",
    bg_cursorline = "#d5d6db",
    bg_selection = "#c4c8da",
    fg = "#3760bf",
    fg_muted = "#6172b0",
    fg_parameter = "#7847bd",
    comment = "#848cb5",
    subtle = "#848cb5",
    gutter = "#d5d6db",
    guide = "#9699a3",
    border = "#9699a3",
    cyan = "#007197",
    green = "#587539",
    orange = "#b15c00",
    amber = "#8c6c3e",
    pink = "#d20065",
    purple = "#7847bd",
    red = "#f52a65",
    yellow = "#8c6c3e",
    sky = "#2e7de9",
    teal = "#33635c",
    blue = "#2e7de9",
    magenta = "#7847bd",
    braces = "#2e7de9",
    brackets = "#33635c",
    parens = "#8c6c3e",
    rainbow = {
      "#7847bd",
      "#d20065",
      "#b15c00",
      "#587539",
      "#007197",
      "#2e7de9",
    },
    none = "NONE",
    terminal = {
      "#d5d6db",
      "#f52a65",
      "#587539",
      "#8c6c3e",
      "#2e7de9",
      "#7847bd",
      "#007197",
      "#3760bf",
      "#a1a6c5",
      "#ff4774",
      "#5c8524",
      "#a27629",
      "#4a88f0",
      "#915caf",
      "#0db9d7",
      "#3760bf",
    },
    background = "light",
  },
}

local function roles(C, O)
  local styles = O.styles or {}

  return {
    text = { fg = C.fg },
    identifier = { fg = C.fg_muted },
    local_variable = { fg = C.fg },
    builtin_variable = { fg = C.red },
    comment = { fg = C.comment, italic = vim.tbl_contains(styles.comments or {}, "italic") },
    keyword = { fg = C.purple },
    preproc = { fg = C.purple },
    function_name = { fg = C.blue },
    function_builtin = { fg = C.cyan },
    type = { fg = C.teal },
    builtin_type = { fg = C.teal },
    type_parameter = { fg = C.amber },
    constructor = { fg = C.teal },
    parameter = { fg = C.yellow, italic = vim.tbl_contains(styles.parameters or {}, "italic") },
    label = { fg = C.orange },
    field = { fg = C.teal },
    property = { fg = C.teal },
    constant = { fg = C.orange },
    macro = { fg = C.red },
    string = { fg = C.green },
    character = { fg = C.green },
    number = { fg = C.orange },
    escape = { fg = C.red },
    regexp = { fg = C.red },
    special = { fg = C.cyan },
    tag = { fg = C.red },
    attribute = { fg = C.amber },
    operator = { fg = C.cyan },
    module = { fg = C.teal },
    uri = { fg = C.blue, underline = true },
    todo = { fg = C.bg, bg = C.yellow, bold = true },
    diagnostic_error = { fg = C.red },
    diagnostic_warn = { fg = C.yellow },
    diagnostic_info = { fg = C.blue },
    diagnostic_hint = { fg = C.teal },
    ui_border = { fg = C.border },
    ui_selection = { bg = C.bg_selection },
    ui_menu = { fg = C.fg, bg = C.bg_float },
  }
end

local function editor_overrides(C)
  return {
    FloatTitle = { fg = C.sky, bg = C.bg_float },
    CursorLineNr = { fg = C.orange, bold = true },
    MatchParen = { fg = C.fg, bg = C.bg_selection, bold = true },
    LineNr = { fg = C.guide },
    EndOfBuffer = { fg = C.guide },
    WildMenu = { fg = C.bg, bg = C.sky, bold = true },
  }
end

local function syntax_overrides(C)
  return {
    Character = { fg = C.green },
    Constant = { fg = C.orange },
    Number = { fg = C.orange },
    Boolean = { fg = C.orange },
    Float = { fg = C.orange },
    StorageClass = { fg = C.purple },
    Structure = { fg = C.teal },
    Special = { fg = C.cyan },
    SpecialChar = { fg = C.cyan },
    Tag = { fg = C.red },
    Conceal = { fg = C.subtle },
    MoreMsg = { fg = C.blue },
    ModeMsg = { fg = C.blue },
    Todo = { fg = C.bg, bg = C.yellow, bold = true },
  }
end

local function treesitter_overrides(C)
  return {
    ["@variable"] = { fg = C.fg },
    ["@variable.builtin"] = { fg = C.red },
    ["@variable.parameter"] = { fg = C.yellow },
    ["@variable.member"] = { fg = C.teal },
    ["@constant"] = { fg = C.orange },
    ["@constant.builtin"] = { fg = C.orange },
    ["@constant.macro"] = { fg = C.red },
    ["@module"] = { fg = C.teal },
    ["@string.documentation"] = { fg = C.green },
    ["@string.escape"] = { fg = C.red },
    ["@string.special.symbol"] = { fg = C.orange },
    ["@type.builtin"] = { fg = C.teal },
    ["@attribute"] = { fg = C.amber },
    ["@property"] = { fg = C.teal },
    ["@function.builtin"] = { fg = C.cyan },
    ["@function.macro"] = { fg = C.red },
    ["@constructor"] = { fg = C.teal },
    ["@keyword.import"] = { fg = C.purple },
    ["@punctuation.bracket"] = { fg = C.fg_muted },
    ["@markup.link"] = { fg = C.blue, underline = true },
    ["@markup.link.label"] = { fg = C.sky },
    ["@markup.link.url"] = { fg = C.blue, underline = true, italic = true },
    ["@markup.quote"] = { fg = C.comment },
    ["@tag"] = { fg = C.red },
    ["@tag.builtin"] = { fg = C.red },
    ["@tag.attribute"] = { fg = C.amber },
    ["@tag.delimiter"] = { fg = C.cyan },
    ["@comment.todo"] = { fg = C.bg, bg = C.yellow, bold = true },
    ["@comment.note"] = { fg = C.bg, bg = C.blue, bold = true },
    ["@comment.warning"] = { fg = C.bg, bg = C.orange, bold = true },
    ["@comment.error"] = { fg = C.bg, bg = C.red, bold = true },
    ["@markup.heading.1.markdown"] = { fg = C.red, bold = true },
    ["@markup.heading.2.markdown"] = { fg = C.orange, bold = true },
    ["@markup.heading.3.markdown"] = { fg = C.yellow, bold = true },
    ["@markup.heading.4.markdown"] = { fg = C.green, bold = true },
    ["@markup.heading.5.markdown"] = { fg = C.cyan, bold = true },
    ["@markup.heading.6.markdown"] = { fg = C.purple, bold = true },
    ["@property.css"] = { fg = C.sky },
    ["@property.scss"] = { fg = C.sky },
    ["@property.id.css"] = { fg = C.amber },
    ["@property.class.css"] = { fg = C.amber },
    ["@type.css"] = { fg = C.teal },
    ["@type.tag.css"] = { fg = C.red },
    ["@number.css"] = { fg = C.orange },
    ["@string.special.url.html"] = { fg = C.green, underline = true },
    ["@markup.link.label.html"] = { fg = C.fg },
    ["@character.special.html"] = { fg = C.red },
    ["@attribute.c_sharp"] = { fg = C.amber },
  }
end

local function semantic_token_overrides(C)
  return {
    ["@lsp.type.enumMember"] = { fg = C.orange },
    ["@lsp.type.parameter"] = { fg = C.yellow },
    ["@lsp.type.property"] = { fg = C.teal },
    ["@lsp.type.variable.readonly"] = { fg = C.orange, bold = true },
    ["@lsp.typemod.function.defaultLibrary"] = { link = "@function.builtin" },
    ["@lsp.typemod.function.builtin"] = { link = "@function.builtin" },
    ["@lsp.typemod.property.defaultLibrary"] = { fg = C.teal },
    ["@lsp.typemod.variable.defaultLibrary"] = { fg = C.red },
    ["@lsp.typemod.variable.globalScope"] = { fg = C.red, bold = true },
    ["@lsp.typemod.variable.readonly"] = { fg = C.orange, bold = true },
    ["@lsp.typemod.variable.static"] = { fg = C.orange, bold = true },
  }
end

local function shared_overrides(C)
  return {
    modules = {
      editor = function()
        return editor_overrides(C)
      end,
      syntax = function()
        return syntax_overrides(C)
      end,
      treesitter = function()
        return treesitter_overrides(C)
      end,
      semantic_tokens = function()
        return semantic_token_overrides(C)
      end,
    },
    integrations = {},
    languages = {},
  }
end

function M.make(flavour)
  local raw = palettes[flavour]
  if not raw then
    error("spectra.nvim: unknown Tokyonight flavour '" .. tostring(flavour) .. "'")
  end

  local colorscheme = "tokyonight-" .. flavour

  return {
    meta = {
      name = colorscheme,
      colorscheme = colorscheme,
      background = raw.background,
      family = "tokyonight",
      flavour = flavour,
    },
    palette = function()
      return vim.deepcopy(raw)
    end,
    roles = roles,
    overrides = shared_overrides(raw),
  }
end

return M
